[package]
name = "solutions"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
bimap = "0.6.3"
ethnum = "1.5.0"
itertools = "0.13.0"
lazy_static = "1.5.0"
libadvent = { workspace = true }
memoize = "0.4.2"
rayon = "1.10.0"


[lints.clippy]
precedence = "allow"
