[package]
name = "solutions"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
ethnum = "1.5.0"
itertools = "0.13.0"
libadvent = { workspace = true }
paste = "1.0.15"
rayon = "1.10.0"


[lints.clippy]
precedence = "allow"
