[package]
name = "advent24-runner"
version = "0.1.0"
edition = "2021"
authors = ["Angad Tendulkar"]

[dependencies]
colored = "2.1.0"
libadvent = { workspace = true }
paste = "1.0.15"
solutions = { path = "../solutions" }
